name: Continuous Integration - Python Package

on:
  workflow_call:
    inputs:
      # Counterintuitive, but this is the value for full history required for rev-list --count
      fetch-depth:
        default: 0
        required: false
        type: number

jobs:
  ci-test-python:
    name: Perform Python CI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_packages/python

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set up Python with Poetry Caching
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: |
            _packages/python/poetry.lock

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          ./update_version.py
          poetry install

      - name: Perform Tests
        run:  poetry run pytest

      - name: Build package
        run: poetry build