name: Ruby Gem CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci-test-gem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install Dependencies
        working-directory: ./_packages/ruby
        run: |
          bundle install

      - name: Perform Default Rake Task
        working-directory: ./_packages/ruby
        run: |
          rake

      - name: Perform Explicit Rake Test
        working-directory: ./_packages/ruby
        run: |
          rake spec
