# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Upload NPM Package

on:
  push:
    branches: [ main ]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    environment: node-push
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: _packages/node/yarn.lock
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./_packages/node
        run: |
          yarn install

      - name: Build package
        working-directory: ./_packages/node
        run: |
          yarn build

      - name: Run Package Tests
        working-directory: ./_packages/node
        run: |
          yarn test

      - name: Publish to NPM Registry
        run: yarn publish
        working-directory: ./_packages/node
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
