name: NPM / Node Package CI

on:
  pull_request:
    branches: [ main ]


jobs:
  ci-test-node:
    name: Perform Node Continuous Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: _packages/node/yarn.lock
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./_packages/node
        run: |
          yarn install

      - name: Perform a Build
        working-directory: ./_packages/node
        run: |
          yarn build

      - name: Run Package Tests
        working-directory: ./_packages/node
        run: |
          yarn test