name: Static Website - Build

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    environment: gh-pages
    steps:
      - uses: actions/checkout@v2

      - id: gem-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: hack-different/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          target_branch: gh-pages
          target_path: /

      - name: Archive Data Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: data-site
          path: _site
