name: Publish Package - Ruby / Rubygems

on:
  push:
    branches: [ main ]

inputs:
  # Counterintuitive, but this is the value for full history required for rev-list --count
  fetch-depth:
    default: 0
    required: false
    type: number

jobs:
  ci-build-ruby:
    needs: ci-test
    uses: hack-different/apple-knowledge/.github/workflows/ruby-ci.yml@main

  publish-gem:
    name: Build + Publish
    runs-on: ubuntu-latest
    environment: gem-push
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - uses: actions/download-artifact@v3
        name: Download Ruby Package Artifacts
        with:
          name: package-gem

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
